name: Build Extension Zip
on:
  workflow_call:
    inputs:
      extensionName:
        description: 'Your extension name'
        required: true
        type: string
jobs:
  run:
    name: Build and Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install haoke-cli
        uses: haokeyingxiao/haoke-cli-action@v1
      - name: Build
        run: haoke-cli extension zip . --git-commit "${{ github.sha }}"
      - name: Rename
        run: mv ${{ inputs.extensionName }}-${{ github.sha }}.zip ${{ inputs.extensionName }}.zip
      - name: Validate
        run: haoke-cli extension validate ${{ inputs.extensionName }}.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.extensionName }}.zip
          path: ${{ inputs.extensionName }}.zip
